export const languages = [
  { code: "en", name: "English" },
  { code: "hi", name: "Hindi" },
  { code: "es", name: "Spanish" },
  { code: "fr", name: "French" },
  { code: "de", name: "German" },
  { code: "it", name: "Italian" },
  { code: "pt", name: "Portuguese" },
  { code: "ru", name: "Russian" },
  { code: "zh", name: "Chinese" },
  { code: "ja", name: "Japanese" },
  { code: "ko", name: "Korean" },
  { code: "ar", name: "Arabic" },
  { code: "tr", name: "Turkish" },
  { code: "nl", name: "Dutch" },
  { code: "sv", name: "Swedish" },
  { code: "no", name: "Norwegian" },
  { code: "da", name: "Danish" },
  { code: "fi", name: "Finnish" },
  { code: "pl", name: "Polish" },
  { code: "cs", name: "Czech" },
  { code: "el", name: "Greek" },
  { code: "he", name: "Hebrew" },
  { code: "th", name: "Thai" },
  { code: "vi", name: "Vietnamese" },
  { code: "id", name: "Indonesian" },
  { code: "ms", name: "Malay" },
  { code: "bn", name: "Bengali" },
  { code: "ta", name: "Tamil" },
  { code: "te", name: "Telugu" },
  { code: "mr", name: "Marathi" },
  { code: "gu", name: "Gujarati" },
  { code: "kn", name: "Kannada" },
  { code: "ml", name: "Malayalam" },
  { code: "pa", name: "Punjabi" },
  { code: "ur", name: "Urdu" }
];


export const channelCategories = [
  { id: 1, code: "news", name: "News" },
  { id: 2, code: "sports", name: "Sports" },
  { id: 3, code: "movies", name: "Movies" },
  { id: 4, code: "music", name: "Music" },
  { id: 5, code: "kids", name: "Kids" },
  { id: 6, code: "entertainment", name: "Entertainment" },
  { id: 7, code: "religious", name: "Religious" },
  { id: 8, code: "education", name: "Education" },
  { id: 9, code: "documentary", name: "Documentary" },
  { id: 10, code: "lifestyle", name: "Lifestyle" },
  { id: 11, code: "business", name: "Business" },
  { id: 12, code: "travel", name: "Travel" },
  { id: 13, code: "food", name: "Food" },
  { id: 14, code: "fashion", name: "Fashion" },
  { id: 15, code: "science", name: "Science" },
  { id: 16, code: "technology", name: "Technology" },
  { id: 17, code: "gaming", name: "Gaming" },
  { id: 18, code: "comedy", name: "Comedy" },
  { id: 19, code: "health", name: "Health & Fitness" },
  { id: 20, code: "weather", name: "Weather" }
];

